apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - port: 21
    targetPort: 21
    name: ftps
  - port: 21000
    targetPort: 21000
    name: ftps-data

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: service_ftps
        imagePullPolicy: Never
        env:
          - name: IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
